### ISSUE TITLE
Train 

### ISSUE THREAD

**Issue by Ystartff** [wurenkai/H-vmunet#4]
I used the breast cancer dataset BUSI for training and pre-processed the data, but I encountered a problem during training
#----------Training----------#
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [32,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [33,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [34,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [35,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [36,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [37,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [38,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [39,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [40,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [41,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [42,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [44,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [46,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [47,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [48,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [49,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [50,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [51,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [52,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [53,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [54,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [55,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [56,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [57,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [58,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [61,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [62,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [63,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [96,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [97,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [98,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [99,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [100,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [101,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [102,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [103,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [104,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [105,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [106,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [107,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [108,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [109,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [110,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [111,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [112,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [113,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [114,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [115,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [116,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [117,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [118,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [119,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [120,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [121,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [122,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [123,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [124,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [125,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [126,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [125,0,0], thread: [127,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [64,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [65,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [66,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [67,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [68,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [69,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [70,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [71,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [72,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [73,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [74,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [75,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [76,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [77,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [78,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [79,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [80,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [81,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [82,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [83,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [84,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [85,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [86,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [87,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [88,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [89,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [90,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [91,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [92,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [93,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [94,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [97,0,0], thread: [95,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [32,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [33,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [34,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [35,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [36,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [37,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [38,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [39,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [40,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [41,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [42,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [44,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [46,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [47,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [48,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [49,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [50,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [51,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [52,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [53,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [54,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [55,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [56,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [57,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [58,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [61,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [62,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [63,0,0] Assertion `input_val >= zero && input_val <= one` failed.
Traceback (most recent call last):
  File "/mnt/data/panxue/PX/H-vmunet-main/train.py", line 188, in <module>
    main(config)
  File "/mnt/data/panxue/PX/H-vmunet-main/train.py", line 131, in main
    train_one_epoch(
  File "/mnt/data/panxue/PX/H-vmunet-main/engine.py", line 40, in train_one_epoch
    loss = criterion(out, targets)
  File "/home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/panxue/PX/H-vmunet-main/utils.py", line 295, in forward
    bceloss = self.bce(pred, target)
  File "/home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/panxue/PX/H-vmunet-main/utils.py", line 266, in forward
    return self.bceloss(pred_, target_)
  File "/home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 618, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/functional.py", line 3122, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [96,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [97,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [98,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [99,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [100,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [101,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [102,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [103,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [104,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [105,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [106,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [107,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [108,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [109,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [110,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [111,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [112,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [113,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [114,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [115,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [116,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [117,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [118,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [119,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [120,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [121,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [122,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [123,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [124,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [125,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [126,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [91,0,0], thread: [127,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [96,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [97,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [98,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [99,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [100,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [101,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [102,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [103,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [104,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [105,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [106,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [107,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [108,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [109,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [110,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [111,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [112,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [113,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [114,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [115,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [116,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [117,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [118,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [119,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [120,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [121,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [122,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [123,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [124,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [125,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [126,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:94: operator(): block: [171,0,0], thread: [127,0,0] Assertion `input_val >= zero && input_val <= one` failed.
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f5b08f06617 in /home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f5b08ec198d in /home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f5b08fb7c38 in /home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x126023e (0x7f5b0a2e223e in /home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x5197b6 (0x7f5b73be47b6 in /home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x55ca7 (0x7f5b08eebca7 in /home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #6: c10::TensorImpl::~TensorImpl() + 0x1e3 (0x7f5b08ee3cb3 in /home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #7: c10::TensorImpl::~TensorImpl() + 0x9 (0x7f5b08ee3e49 in /home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #8: <unknown function> + 0x7c9738 (0x7f5b73e94738 in /home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #9: THPVariable_subclass_dealloc(_object*) + 0x305 (0x7f5b73e94ac5 in /home/panxue/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #10: python() [0x4dd8e4]
frame #11: python() [0x4f5d58]
frame #12: python() [0x505859]
frame #13: python() [0x5058bb]
frame #14: python() [0x5058bb]
frame #15: python() [0x4deed2]
<omitting python frames>
frame #17: python() [0x5c3dd4]
frame #21: __libc_start_main + 0xf3 (0x7f5ba36d4083 in /lib/x86_64-linux-gnu/libc.so.6)
frame #22: python() [0x584cfe]

已放弃 (核心已转储)

**Comment by wurenkai** [comment]
Hi, based on your error message, we believe that there was an [issue](https://github.com/wurenkai/UltraLight-VM-UNet/issues/6) when you were preparing the data that caused a mismatch of data values in the first layer of the input convolution. You should be able to get help from that issue. The number of training, validation and test sets should be accurately divided and formatted correctly to be imported into the '.npy' file. Best regards.

**Comment by Ystartff** [comment]
I handled the data preprocessing, and but I printed the size before it was originally passed into the model as x torch.Size([8, 3, 256, 256]).The 647 at the beginning represents the number of my BUSI datasets, and I completed the process according to 6:2:2, but still met the following problem.I changed num_classes to 2, but found that the following happens when set to 1 as well
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
Reading your dataset finished
(tool) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ python train.py
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
(tool) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ conda activate vmunet
(vmunet) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ python train.py
#----------Creating logger----------#
#----------GPU init----------#
#----------Preparing dataset----------#
#----------Prepareing Models----------#
[H_SS2D] 2 order with dims= [8, 16] scale=0.3333
[H_SS2D] 2 order with dims= [8, 16] scale=0.3333
[H_SS2D] 3 order with dims= [8, 16, 32] scale=0.3333
[H_SS2D] 3 order with dims= [8, 16, 32] scale=0.3333
[H_SS2D] 4 order with dims= [8, 16, 32, 64] scale=0.3333
[H_SS2D] 4 order with dims= [8, 16, 32, 64] scale=0.3333
[H_SS2D] 5 order with dims= [8, 16, 32, 64, 128] scale=0.3333
[H_SS2D] 5 order with dims= [8, 16, 32, 64, 128] scale=0.3333
SC_Att_Bridge was used
[H_SS2D] 5 order with dims= [16, 32, 64, 128, 256] scale=0.3333
[H_SS2D] 5 order with dims= [16, 32, 64, 128, 256] scale=0.3333
[H_SS2D] 4 order with dims= [16, 32, 64, 128] scale=0.3333
[H_SS2D] 4 order with dims= [16, 32, 64, 128] scale=0.3333
[H_SS2D] 3 order with dims= [16, 32, 64] scale=0.3333
[H_SS2D] 3 order with dims= [16, 32, 64] scale=0.3333
[H_SS2D] 2 order with dims= [16, 32] scale=0.3333
[H_SS2D] 2 order with dims= [16, 32] scale=0.3333
#----------Prepareing loss, opt, sch and amp----------#
#----------Set other params----------#
#----------Training----------#
Traceback (most recent call last):
  File "train.py", line 188, in <module>
    main(config)
  File "train.py", line 131, in main
    train_one_epoch(
  File "/mnt/data/panxue/PX/H-vmunet-main/engine.py", line 38, in train_one_epoch
    out = model(images)
  File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data/panxue/PX/H-vmunet-main/models/H_vmunet.py", line 381, in forward
    out = F.gelu(F.max_pool2d(self.ebn1(self.encoder1(x)),2,2))
  File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: no valid convolution algorithms available in CuDNN

**Comment by Ystartff** [comment]
> I handled the data preprocessing, and but I printed the size before it was originally passed into the model as x torch.Size([8, 3, 256, 256]).The 647 at the beginning represents the number of my BUSI datasets, and I completed the process according to 6:2:2, but still met the following problem.I changed num_classes to 2, but found that the following happens when set to 1 as well 628 629 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 Reading your dataset finished (tool) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ python train.py Traceback (most recent call last): File "train.py", line 1, in import torch ModuleNotFoundError: No module named 'torch' (tool) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ conda activate vmunet (vmunet) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ python train.py #----------Creating logger----------# #----------GPU init----------# #----------Preparing dataset----------# #----------Prepareing Models----------# [H_SS2D] 2 order with dims= [8, 16] scale=0.3333 [H_SS2D] 2 order with dims= [8, 16] scale=0.3333 [H_SS2D] 3 order with dims= [8, 16, 32] scale=0.3333 [H_SS2D] 3 order with dims= [8, 16, 32] scale=0.3333 [H_SS2D] 4 order with dims= [8, 16, 32, 64] scale=0.3333 [H_SS2D] 4 order with dims= [8, 16, 32, 64] scale=0.3333 [H_SS2D] 5 order with dims= [8, 16, 32, 64, 128] scale=0.3333 [H_SS2D] 5 order with dims= [8, 16, 32, 64, 128] scale=0.3333 SC_Att_Bridge was used [H_SS2D] 5 order with dims= [16, 32, 64, 128, 256] scale=0.3333 [H_SS2D] 5 order with dims= [16, 32, 64, 128, 256] scale=0.3333 [H_SS2D] 4 order with dims= [16, 32, 64, 128] scale=0.3333 [H_SS2D] 4 order with dims= [16, 32, 64, 128] scale=0.3333 [H_SS2D] 3 order with dims= [16, 32, 64] scale=0.3333 [H_SS2D] 3 order with dims= [16, 32, 64] scale=0.3333 [H_SS2D] 2 order with dims= [16, 32] scale=0.3333 [H_SS2D] 2 order with dims= [16, 32] scale=0.3333 #----------Prepareing loss, opt, sch and amp----------# #----------Set other params----------# #----------Training----------# Traceback (most recent call last): File "train.py", line 188, in main(config) File "train.py", line 131, in main train_one_epoch( File "/mnt/data/panxue/PX/H-vmunet-main/engine.py", line 38, in train_one_epoch out = model(images) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward return self.module(*inputs[0], **kwargs[0]) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/mnt/data/panxue/PX/H-vmunet-main/models/H_vmunet.py", line 381, in forward out = F.gelu(F.max_pool2d(self.ebn1(self.encoder1(x)),2,2)) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward input = module(input) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward return self._conv_forward(input, self.weight, self.bias) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward return F.conv2d(input, weight, bias, self.stride, RuntimeError: no valid convolution algorithms available in CuDNN


This is my modified data preprocessing
train_number = 389 # Randomly assign the number of images for generating the training set.
val_number = 129   # Randomly assign the number of images for generating the validation set.
test_number = 129  # Randomly assign the number of images for generating the test set.
all = int(train_number) + int(val_number) + int(test_number)

############################################################# Prepare your data set #################################################
image_dir = "/mnt/data/panxue/PX/H-vmunet-main/data/images"
Tr_list = [os.path.join(image_dir, f) for f in os.listdir(image_dir) if f.endswith('.png')]
  # Images storage folder. The image type should be 24-bit png format.
# It contains 2594 training samples
Data_train_2018    = np.zeros([all, height, width, channels])
Label_train_2018   = np.zeros([all, height, width])

print('Reading')
print(len(Tr_list))
for idx in range(len(Tr_list)):
    print(idx+1)
    img = sc.imread(Tr_list[idx])
    img = np.double(sc.imresize(img, [height, width, channels], interp='bilinear', mode = 'RGB'))
    Data_train_2018[idx, :,:,:] = img

    b = Tr_list[idx]
    b = b[b.rfind('/') + 1:len(b) - 4]


    add = ("/mnt/data/panxue/PX/H-vmunet-main/data/masks/" + b +'_mask.png')  # Masks storage folder. The Mask type should be a black and white image of an 8-bit png (0 pixels for the background and 255 pixels for the target).
    img2 = sc.imread(add)
    img2 = np.double(sc.imresize(img2, [height, width], interp='bilinear'))
    Label_train_2018[idx, :,:] = img2    
         
print('Reading your dataset finished')

**Comment by Ystartff** [comment]
> I handled the data preprocessing, and but I printed the size before it was originally passed into the model as x torch.Size([8, 3, 256, 256]).The 647 at the beginning represents the number of my BUSI datasets, and I completed the process according to 6:2:2, but still met the following problem.I changed num_classes to 2, but found that the following happens when set to 1 as well 628 629 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 Reading your dataset finished (tool) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ python train.py Traceback (most recent call last): File "train.py", line 1, in import torch ModuleNotFoundError: No module named 'torch' (tool) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ conda activate vmunet (vmunet) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ python train.py #----------Creating logger----------# #----------GPU init----------# #----------Preparing dataset----------# #----------Prepareing Models----------# [H_SS2D] 2 order with dims= [8, 16] scale=0.3333 [H_SS2D] 2 order with dims= [8, 16] scale=0.3333 [H_SS2D] 3 order with dims= [8, 16, 32] scale=0.3333 [H_SS2D] 3 order with dims= [8, 16, 32] scale=0.3333 [H_SS2D] 4 order with dims= [8, 16, 32, 64] scale=0.3333 [H_SS2D] 4 order with dims= [8, 16, 32, 64] scale=0.3333 [H_SS2D] 5 order with dims= [8, 16, 32, 64, 128] scale=0.3333 [H_SS2D] 5 order with dims= [8, 16, 32, 64, 128] scale=0.3333 SC_Att_Bridge was used [H_SS2D] 5 order with dims= [16, 32, 64, 128, 256] scale=0.3333 [H_SS2D] 5 order with dims= [16, 32, 64, 128, 256] scale=0.3333 [H_SS2D] 4 order with dims= [16, 32, 64, 128] scale=0.3333 [H_SS2D] 4 order with dims= [16, 32, 64, 128] scale=0.3333 [H_SS2D] 3 order with dims= [16, 32, 64] scale=0.3333 [H_SS2D] 3 order with dims= [16, 32, 64] scale=0.3333 [H_SS2D] 2 order with dims= [16, 32] scale=0.3333 [H_SS2D] 2 order with dims= [16, 32] scale=0.3333 #----------Prepareing loss, opt, sch and amp----------# #----------Set other params----------# #----------Training----------# Traceback (most recent call last): File "train.py", line 188, in main(config) File "train.py", line 131, in main train_one_epoch( File "/mnt/data/panxue/PX/H-vmunet-main/engine.py", line 38, in train_one_epoch out = model(images) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward return self.module(*inputs[0], **kwargs[0]) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/mnt/data/panxue/PX/H-vmunet-main/models/H_vmunet.py", line 381, in forward out = F.gelu(F.max_pool2d(self.ebn1(self.encoder1(x)),2,2)) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward input = module(input) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward return self._conv_forward(input, self.weight, self.bias) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward return F.conv2d(input, weight, bias, self.stride, RuntimeError: no valid convolution algorithms available in CuDNN

This is my modified data preprocessing
train_number = 389 # Randomly assign the number of images for generating the training set.
val_number = 129   # Randomly assign the number of images for generating the validation set.
test_number = 129  # Randomly assign the number of images for generating the test set.
all = int(train_number) + int(val_number) + int(test_number)

############################################################# Prepare your data set #################################################
image_dir = "/mnt/data/panxue/PX/H-vmunet-main/data/images"
Tr_list = [os.path.join(image_dir, f) for f in os.listdir(image_dir) if f.endswith('.png')]
  # Images storage folder. The image type should be 24-bit png format.
# It contains 2594 training samples
Data_train_2018    = np.zeros([all, height, width, channels])
Label_train_2018   = np.zeros([all, height, width])

print('Reading')
print(len(Tr_list))
for idx in range(len(Tr_list)):
    print(idx+1)
    img = sc.imread(Tr_list[idx])
    img = np.double(sc.imresize(img, [height, width, channels], interp='bilinear', mode = 'RGB'))
    Data_train_2018[idx, :,:,:] = img

    b = Tr_list[idx]
    b = b[b.rfind('/') + 1:len(b) - 4]


    add = ("/mnt/data/panxue/PX/H-vmunet-main/data/masks/" + b +'_mask.png')  # Masks storage folder. The Mask type should be a black and white image of an 8-bit png (0 pixels for the background and 255 pixels for the target).
    img2 = sc.imread(add)
    img2 = np.double(sc.imresize(img2, [height, width], interp='bilinear'))
    Label_train_2018[idx, :,:] = img2    
         
print('Reading your dataset finished')

**Comment by Ystartff** [comment]
> I handled the data preprocessing, and but I printed the size before it was originally passed into the model as x torch.Size([8, 3, 256, 256]).The 647 at the beginning represents the number of my BUSI datasets, and I completed the process according to 6:2:2, but still met the following problem.I changed num_classes to 2, but found that the following happens when set to 1 as well 628 629 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 Reading your dataset finished (tool) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ python train.py Traceback (most recent call last): File "train.py", line 1, in import torch ModuleNotFoundError: No module named 'torch' (tool) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ conda activate vmunet (vmunet) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ python train.py #----------Creating logger----------# #----------GPU init----------# #----------Preparing dataset----------# #----------Prepareing Models----------# [H_SS2D] 2 order with dims= [8, 16] scale=0.3333 [H_SS2D] 2 order with dims= [8, 16] scale=0.3333 [H_SS2D] 3 order with dims= [8, 16, 32] scale=0.3333 [H_SS2D] 3 order with dims= [8, 16, 32] scale=0.3333 [H_SS2D] 4 order with dims= [8, 16, 32, 64] scale=0.3333 [H_SS2D] 4 order with dims= [8, 16, 32, 64] scale=0.3333 [H_SS2D] 5 order with dims= [8, 16, 32, 64, 128] scale=0.3333 [H_SS2D] 5 order with dims= [8, 16, 32, 64, 128] scale=0.3333 SC_Att_Bridge was used [H_SS2D] 5 order with dims= [16, 32, 64, 128, 256] scale=0.3333 [H_SS2D] 5 order with dims= [16, 32, 64, 128, 256] scale=0.3333 [H_SS2D] 4 order with dims= [16, 32, 64, 128] scale=0.3333 [H_SS2D] 4 order with dims= [16, 32, 64, 128] scale=0.3333 [H_SS2D] 3 order with dims= [16, 32, 64] scale=0.3333 [H_SS2D] 3 order with dims= [16, 32, 64] scale=0.3333 [H_SS2D] 2 order with dims= [16, 32] scale=0.3333 [H_SS2D] 2 order with dims= [16, 32] scale=0.3333 #----------Prepareing loss, opt, sch and amp----------# #----------Set other params----------# #----------Training----------# Traceback (most recent call last): File "train.py", line 188, in main(config) File "train.py", line 131, in main train_one_epoch( File "/mnt/data/panxue/PX/H-vmunet-main/engine.py", line 38, in train_one_epoch out = model(images) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward return self.module(*inputs[0], **kwargs[0]) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/mnt/data/panxue/PX/H-vmunet-main/models/H_vmunet.py", line 381, in forward out = F.gelu(F.max_pool2d(self.ebn1(self.encoder1(x)),2,2)) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward input = module(input) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward return self._conv_forward(input, self.weight, self.bias) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward return F.conv2d(input, weight, bias, self.stride, RuntimeError: no valid convolution algorithms available in CuDNN

This is my modified data preprocessing

train_number = 389 
val_number = 129   
test_number = 129  
all = int(train_number) + int(val_number) + int(test_number)
image_dir = "/mnt/data/panxue/PX/H-vmunet-main/data/images"
Tr_list = [os.path.join(image_dir, f) for f in os.listdir(image_dir) if f.endswith('.png')]
Data_train_2018    = np.zeros([all, height, width, channels])
Label_train_2018   = np.zeros([all, height, width])
print('Reading')
print(len(Tr_list))
for idx in range(len(Tr_list)):
    print(idx+1)
    img = sc.imread(Tr_list[idx])
    img = np.double(sc.imresize(img, [height, width, channels], interp='bilinear', mode = 'RGB'))
    Data_train_2018[idx, :,:,:] = img
    b = Tr_list[idx]
    b = b[b.rfind('/') + 1:len(b) - 4]
    add = ("/mnt/data/panxue/PX/H-vmunet-main/data/masks/" + b +'_mask.png') 
    img2 = sc.imread(add)
    img2 = np.double(sc.imresize(img2, [height, width], interp='bilinear'))
    Label_train_2018[idx, :,:] = img2       
print('Reading your dataset finished')

**Comment by Ystartff** [comment]
print('Train_img shape:', Train_img.shape)
print('Validation_img shape:', Validation_img.shape)
print('Test_img shape:', Test_img.shape)
print('Train_mask shape:', Train_mask.shape)
print('Validation_mask shape:', Validation_mask.shape)
print('Test_mask shape:', Test_mask.shape)

Train_img shape: (389, 256, 256, 3)
Validation_img shape: (129, 256, 256, 3)
Test_img shape: (129, 256, 256, 3)
Train_mask shape: (389, 256, 256)
Validation_mask shape: (129, 256, 256)
Test_mask shape: (129, 256, 256)


> > I handled the data preprocessing, and but I printed the size before it was originally passed into the model as x torch.Size([8, 3, 256, 256]).The 647 at the beginning represents the number of my BUSI datasets, and I completed the process according to 6:2:2, but still met the following problem.I changed num_classes to 2, but found that the following happens when set to 1 as well 628 629 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 Reading your dataset finished (tool) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ python train.py Traceback (most recent call last): File "train.py", line 1, in import torch ModuleNotFoundError: No module named 'torch' (tool) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ conda activate vmunet (vmunet) panxue@user-NF5280M5:/mnt/data/panxue/PX/H-vmunet-main$ python train.py #----------Creating logger----------# #----------GPU init----------# #----------Preparing dataset----------# #----------Prepareing Models----------# [H_SS2D] 2 order with dims= [8, 16] scale=0.3333 [H_SS2D] 2 order with dims= [8, 16] scale=0.3333 [H_SS2D] 3 order with dims= [8, 16, 32] scale=0.3333 [H_SS2D] 3 order with dims= [8, 16, 32] scale=0.3333 [H_SS2D] 4 order with dims= [8, 16, 32, 64] scale=0.3333 [H_SS2D] 4 order with dims= [8, 16, 32, 64] scale=0.3333 [H_SS2D] 5 order with dims= [8, 16, 32, 64, 128] scale=0.3333 [H_SS2D] 5 order with dims= [8, 16, 32, 64, 128] scale=0.3333 SC_Att_Bridge was used [H_SS2D] 5 order with dims= [16, 32, 64, 128, 256] scale=0.3333 [H_SS2D] 5 order with dims= [16, 32, 64, 128, 256] scale=0.3333 [H_SS2D] 4 order with dims= [16, 32, 64, 128] scale=0.3333 [H_SS2D] 4 order with dims= [16, 32, 64, 128] scale=0.3333 [H_SS2D] 3 order with dims= [16, 32, 64] scale=0.3333 [H_SS2D] 3 order with dims= [16, 32, 64] scale=0.3333 [H_SS2D] 2 order with dims= [16, 32] scale=0.3333 [H_SS2D] 2 order with dims= [16, 32] scale=0.3333 #----------Prepareing loss, opt, sch and amp----------# #----------Set other params----------# #----------Training----------# Traceback (most recent call last): File "train.py", line 188, in main(config) File "train.py", line 131, in main train_one_epoch( File "/mnt/data/panxue/PX/H-vmunet-main/engine.py", line 38, in train_one_epoch out = model(images) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward return self.module(*inputs[0], **kwargs[0]) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/mnt/data/panxue/PX/H-vmunet-main/models/H_vmunet.py", line 381, in forward out = F.gelu(F.max_pool2d(self.ebn1(self.encoder1(x)),2,2)) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward input = module(input) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward return self._conv_forward(input, self.weight, self.bias) File "/home/panxue/anaconda3/envs/vmunet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward return F.conv2d(input, weight, bias, self.stride, RuntimeError: no valid convolution algorithms available in CuDNN
> 
> This is my modified data preprocessing
> 
> train_number = 389 val_number = 129 test_number = 129 all = int(train_number) + int(val_number) + int(test_number) image_dir = "/mnt/data/panxue/PX/H-vmunet-main/data/images" Tr_list = [os.path.join(image_dir, f) for f in os.listdir(image_dir) if f.endswith('.png')] Data_train_2018 = np.zeros([all, height, width, channels]) Label_train_2018 = np.zeros([all, height, width]) print('Reading') print(len(Tr_list)) for idx in range(len(Tr_list)): print(idx+1) img = sc.imread(Tr_list[idx]) img = np.double(sc.imresize(img, [height, width, channels], interp='bilinear', mode = 'RGB')) Data_train_2018[idx, :,:,:] = img b = Tr_list[idx] b = b[b.rfind('/') + 1:len(b) - 4] add = ("/mnt/data/panxue/PX/H-vmunet-main/data/masks/" + b +'_mask.png') img2 = sc.imread(add) img2 = np.double(sc.imresize(img2, [height, width], interp='bilinear')) Label_train_2018[idx, :,:] = img2 print('Reading your dataset finished')

**Comment by wurenkai** [comment]
Hi, we followed your steps and performed the preprocessing of 647 images (images are 24-bit png, masks are 8-bit png (0 pixels for background, 255 pixels for target)). We ran the training H-vmunet normally.
We recommend that you check the data '.npy' file and generate an image from the '.npy' file to check if it is correct. Generate image from '.npy' (32-bit png image) Code:
```
import matplotlib.pyplot as plt
import numpy as np
import scipy.misc
import os
from skimage.transform import resize
from PIL import Image
 
file_dir = r"train_mask.npy"  # npy file address.
dest_dir = r"./label_train" # Generate png images save address.
 
def npy_png(file_dir, dest_dir):
    if not os.path.exists(file_dir):
        os.makedirs(file_dir)
    if not os.path.exists(dest_dir):
        os.makedirs(dest_dir)
 
    #file = file_dir #+ 'name.npy'  
    con_arr = np.load(file_dir)  
    for i in range(0, 9999):  
        arr = con_arr[i, :, :]  
        disp_to_img = resize(arr, [256, 256])  
        a = format(i, '04d')
        disp_to_img = disp_to_img.astype('uint8')
        plt.imsave(os.path.join(dest_dir, a+".png"), disp_to_img, cmap='gray')  # Select 'gray' for masks. 'plasma' for images.
        print('photo a finished')
 
 
if __name__ == "__main__":
    npy_png(file_dir, dest_dir)

```
![image](https://github.com/wurenkai/H-vmunet/assets/124028634/c3a07730-d222-4de4-adc2-32add6ab4eca)
![image](https://github.com/wurenkai/H-vmunet/assets/124028634/d1447bb9-f1ca-4c32-9231-98dab4c07a76)

**Comment by wurenkai** [comment]
Also, may I ask if you have ever had a dataset that we provided (e.g. ISIC2017 dataset) run properly? This might give you a template to prepare your own dataset, while eliminating system hardware and environment issues.

**Comment by Ystartff** [comment]
Thanks to the author's answer, we carefully studied the delineated files and found that the problem was in the environment, we reinstalled the environment to solve the problem

**Comment by 730432ch** [comment]
> Also, may I ask if you have ever had a dataset that we provided (e.g. ISIC2017 dataset) run properly? This might give you a template to prepare your own dataset, while eliminating system hardware and environment issues.

您好我的loss出现nan的情况你可以给解决以下吗这是我的train.py的代码import torch
from torch import nn
from torch.cuda.amp import autocast, GradScaler
from torch.utils.data import DataLoader
from loader import *

from models.H_vmunet import H_vmunet
from engine import *
import os
import sys
os.environ["CUDA_VISIBLE_DEVICES"] = "0" # "0, 1, 2, 3"
# os.environ["CUDA_LAUNCH_BLOCKING"] = "1"  # 添加这一行用于调试

from utils import *
from configs.config_setting import setting_config

import warnings
warnings.filterwarnings("ignore")

def main(config):

    print('#----------Creating logger----------#')
    sys.path.append(config.work_dir + '/')
    log_dir = os.path.join(config.work_dir, 'log')
    checkpoint_dir = os.path.join(config.work_dir, 'checkpoints')
    resume_model = os.path.join(checkpoint_dir, 'latest.pth')
    outputs = os.path.join(config.work_dir, 'outputs')
    if not os.path.exists(checkpoint_dir):
        os.makedirs(checkpoint_dir)
    if not os.path.exists(outputs):
        os.makedirs(outputs)

    global logger
    logger = get_logger('train', log_dir)

    log_config_info(config, logger)





    print('#----------GPU init----------#')
    set_seed(config.seed)
    gpu_ids = [0]# [0, 1, 2, 3]
    
    # 修改cuDNN配置 - 更保守的设置
    torch.backends.cudnn.enabled = True
    torch.backends.cudnn.benchmark = False  # 先禁用benchmark
    torch.backends.cudnn.deterministic = True  # 使用确定性算法
    
    # 设置允许的卷积算法
    torch.backends.cudnn.allow_tf32 = False  # 禁用TF32以获得更好的数值稳定性
    
    torch.cuda.empty_cache()
    





    print('#----------Preparing dataset----------#')
    train_dataset = isic_loader(path_Data = config.data_path, train = True)
    train_loader = DataLoader(train_dataset,
                                batch_size=config.batch_size, 
                                shuffle=True,
                                pin_memory=True,
                                num_workers=config.num_workers)
    val_dataset = isic_loader(path_Data = config.data_path, train = False)
    val_loader = DataLoader(val_dataset,
                                batch_size=1,
                                shuffle=False,
                                pin_memory=True, 
                                num_workers=config.num_workers,
                                drop_last=True)
    test_dataset = isic_loader(path_Data = config.data_path, train = False, Test = True)
    test_loader = DataLoader(test_dataset,
                                batch_size=1,
                                shuffle=False,
                                pin_memory=True, 
                                num_workers=config.num_workers,
                                drop_last=True)




    print('#----------Prepareing Models----------#')
    model_cfg = config.model_config
    model = H_vmunet(num_classes=model_cfg['num_classes'], 
                    input_channels=model_cfg['input_channels'], 
                    c_list=model_cfg['c_list'], 
                    split_att=model_cfg['split_att'], 
                    bridge=model_cfg['bridge'],
                    drop_path_rate=model_cfg['drop_path_rate'])
    
    model = torch.nn.DataParallel(model.cuda(), device_ids=gpu_ids, output_device=gpu_ids[0])





    print('#----------Prepareing loss, opt, sch and amp----------#')
    # criterion = config.criterion
    # 修改损失函数：使用 BCEWithLogitsLoss 替代 BCEWithLogitsLoss
    # BCEWithLogitsLoss 内置了sigmoid和数值稳定性
    criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor([1.0]).cuda())
    optimizer = get_optimizer(config, model)
    scheduler = get_scheduler(config, optimizer)
    # scaler = GradScaler()
    scaler = GradScaler(enabled=config.amp)  # 根据amp设置启用scaler





    print('#----------Set other params----------#')
    min_loss = 999
    start_epoch = 1
    min_epoch = 1





    if os.path.exists(resume_model):
        print('#----------Resume Model and Other params----------#')
        checkpoint = torch.load(resume_model, map_location=torch.device('cpu'))
        model.module.load_state_dict(checkpoint['model_state_dict'])
        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
        saved_epoch = checkpoint['epoch']
        start_epoch += saved_epoch
        min_loss, min_epoch, loss = checkpoint['min_loss'], checkpoint['min_epoch'], checkpoint['loss']

        log_info = f'resuming model from {resume_model}. resume_epoch: {saved_epoch}, min_loss: {min_loss:.4f}, min_epoch: {min_epoch}, loss: {loss:.4f}'
        logger.info(log_info)





    print('#----------Training----------#')
    for epoch in range(start_epoch, config.epochs + 1):

        torch.cuda.empty_cache()
        # 减小第一个epoch的batch size来测试稳定性
        if epoch == 1:
            original_batch_size = config.batch_size
            config.batch_size = min(config.batch_size, 4)  # 使用较小的batch size开始


        train_one_epoch(
            train_loader,
            model,
            criterion,
            optimizer,
            scheduler,
            epoch,
            logger,
            config,
            scaler=scaler
        )
        # 恢复原始batch size
        if epoch == 1:
            config.batch_size = original_batch_size

        loss = val_one_epoch(
                val_loader,
                model,
                criterion,
                epoch,
                logger,
                config
            )


        if loss < min_loss:
            torch.save(model.module.state_dict(), os.path.join(checkpoint_dir, 'best.pth'))
            min_loss = loss
            min_epoch = epoch

        torch.save(
            {
                'epoch': epoch,
                'min_loss': min_loss,
                'min_epoch': min_epoch,
                'loss': loss,
                'model_state_dict': model.module.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'scheduler_state_dict': scheduler.state_dict(),
            }, os.path.join(checkpoint_dir, 'latest.pth')) 

    if os.path.exists(os.path.join(checkpoint_dir, 'best.pth')):
        print('#----------Testing----------#')
        best_weight = torch.load(config.work_dir + 'checkpoints/best.pth', map_location=torch.device('cpu'))
        model.module.load_state_dict(best_weight)
        loss = test_one_epoch(
                test_loader,
                model,
                criterion,
                logger,
                config,
            )
        os.rename(
            os.path.join(checkpoint_dir, 'best.pth'),
            os.path.join(checkpoint_dir, f'best-epoch{min_epoch}-loss{min_loss:.4f}.pth')
        )      


if __name__ == '__main__':
    config = setting_config
    main(config)
